use_default_settings: true

general:
  instance_name: "Pillywiggins Search"

search:
  autocomplete: "google"
  default_lang: ""
  formats:
    - html
    - json

server:
  secret_key: "${SEARXNG_SECRET:-changeme}"
  limiter: false
  image_proxy: false

engines:
  - name: wolframalpha
    disabled: false
  - name: arxiv
    disabled: false
  - name: google scholar
    disabled: false
  - name: pubmed
    disabled: false
  - name: reddit
    disabled: false
  - name: bing images
    disabled: false
  - name: google images
    disabled: false
  - name: youtube
    disabled: false